---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radarr

resources:
  - base/pvc.yaml
  - base/configmap-webui-fix.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml

commonLabels:
  app: qbittorrent
  managed-by: argocd
